[dependencies]
distance = "0.4.0"

[dependencies.macron]
features = ["derive", "string", "collections"]
version = "^0.1.10"

[package]
authors = ["Fuderis <t.me/fuderis>"]
categories = ["development-tools"]
description = "Fast extractive text summarizer in Rust (with 30-70% compression)."
edition = "2024"
keywords = ["text", "summarize"]
license = "MIT"
name = "simple-summarize"
readme = "README.md"
repository = "https://github.com/fuderis/rs-simple-summarize"
version = "0.1.0"
