[package]
name = "simple-summarize"
description = "Fast extractive text/markdown summarizer (no LLM)."
keywords = ["text", "markdown", "summarize", "compress"]
categories = ["development-tools"]
version = "0.2.1"
authors = ["Bulat Sh. <synapdrake@ya.ru>"]
repository = "https://github.com/fuderis/rs-simple-summarize"
edition = "2024"
license = "MIT"
readme = "README.md"

[dependencies]
macron = { version = "^0.5.0", features = ["derive", "string", "collections"] }
ahash = { version = "0.8.12", features = ["serde"] }
distance = "0.4.0"
serde = { version = "1.0.229", features = ["derive"] }
markdown = { version = "1.0.0", optional = true }
regex = { version = "1.13.1", optional = true }

[features]
full = ["markdown"]
markdown = ["dep:markdown", "dep:regex"]
