type = "crate"

[project]
name = "Simple Summarize"
description = "Fast extractive text summarizer in Rust (with 30-70% compression)."
keywords = ["text", "summarize"]
categories = ["development-tools"]
version = "0.1.0"
authors = ["Fuderis <t.me/fuderis>"]
repository = "https://github.com/fuderis/rs-simple-summarize"
ident = "com.fuderis.rs-simple-summarize"
icon = "icon.ico"
